---
title: "한국어 임베딩과 R"
author: 홍성학
date: 2022년 9월 20일
output: 
  revealjs::revealjs_presentation:
    theme: sky
    highlight: pygments
    center: true
    includes:
      in_header: header.html
      before_body: doc_prefix.html
      after_body: doc_suffix.html
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<style>
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap');

@font-face {
    font-family: 'NEXON Lv1 Gothic OTF';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/NEXON Lv1 Gothic OTF.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'GongGothicMedium';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10@1.0/GongGothicMedium.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'GongGothicBold';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10@1.0/GongGothicBold.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'GongGothicLight';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10@1.0/GongGothicLight.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'ONE-Mobile-Regular';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105_2@1.0/ONE-Mobile-Regular.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'ONE-Mobile-Title';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105_2@1.0/ONE-Mobile-Title.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
</style>
```{css css-settings, echo=FALSE}
.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
  font-family: 'GongGothicLight', 'Noto Sans KR', sans-serif;
}

.reveal .slide {
  font-family: 'ONE-Mobile-Regular', 'Nexon Lv1 Gothic OTF', 'Noto Sans KR', sans-serif;
}

.reveal .author {
  font-family: 'Nexon Lv1 Gothic OTF', 'Noto Sans KR', sans-serif;
}
.reveal .date {
  font-family: 'Nexon Lv1 Gothic OTF', 'Noto Sans KR', sans-serif;
}
```

내용 contents
========================================================

- 한국어 자연어 처리와 텍스트마아닝
- word2vec을 통한 워드임베딩
- 한국어 워드임베딩
- 워드임베딩과 R 패키지
- 워드임베딩의 응용

한국어 자연어 처리와 텍스트마이닝의 현재 
========================================================

- 한국어 자연어처리와 텍스트마이닝은 역사는 오래되었지만 발전이 한계에 부딪힌 것도 오래되었음
- 여전히 쓸만하지 않은 형태소분석기, 구문분석기
    - 더 이상 큰 진척이 없음

자연어처리의 장벽이 되는 한국어의 문제
========================================================

- 띄어쓰기 (spacing problem)
- 복합명사 (compound-noun)
- 조사 (josa)
- 파생접미사

자연어처리의 장벽이 되는 한국어의 문제 - 띄어쓰기
========================================================

띄어쓰기는 됨

아버지가방에들어가신다. -> 아버지가 방에 들어가신다.

붙이기는 안됨

아버지 가방을 고쳐드렸다. -> 아버지가방을 고쳐드렸다. (안됨)

자연어처리의 장벽이 되는 한국어의 문제 - 복합명사 #1
========================================================

개체명 (Named Entity)

- 카라마조프가의 형제들
- 추락하는 것은 날개가 있다
- 오징어게임
- 이상한 변호사 우영우

책이나 영화제목 등의 문장형 이름의 어려움
다른 언어도 동일한 문제가 있음

자연어처리의 장벽이 되는 한국어의 문제 - 복합명사 #2
========================================================

개체명 (Named Entity)

- 대한민국은 민주주의 공회곰이다.
- 한국R사용자커뮤니티는 R을 사용하는 사람들의 커뮤니티이다.

공개된 자료가 없은 한국의 자연어처리의 문제
========================================================

- 모두의 말뭉치(21세기세종계획)
- 위키피디아
- 그외의 자료들

지금까지의 자연어처리와 텍스트마이닝
========================================================

- 워드클라우드
- 토픽모델링
- 단어가방 기반의 기계학습, 마이닝 알고리즘 적용

지금까지의 자연어처리의 문제
========================================================

- 온톨로지의 실패
- 형태소분석기와 구문분석기의 보편화 실패
    - 빅테크 회사내에서만 독점적 관리

언어를 인코딩하는 2가지 기본 방법
========================================================

- TF-IDF 스킴
- 원핫(One hot encoding)


언어를 인코딩하는 2가지 기본 방법 - TFIDF
========================================================

Term Frequency Inverse Document Frequency 

- TF: 토큰의 갯수
- DF: 토큰의 출현한 고유 문서 수


언어를 인코딩하는 2가지 기본 방법 - TFIDF
========================================================

Term Frequency Inverse Document Frequency


언어를 인코딩하는 2가지 기본 방법 - 워드임베딩
========================================================

지전한 윈도우 내의 모든 단어(토큰)을 원핫벡토로 바꿈

원문: "자율주행 자동차는 기계각 운전하는 자동차를 말한다."


TF-IDF와 word2vec 계열의 차이
========================================================

- TF-IDF: Bag of Words (단어가방), 단어 순서가 고려되지 않음
- word2vec: 단어의 순서가 고려됨


워드임베딩 
========================================================

- Word2Vec
- GLoVe
- FastText
- BERT

워드임베딩 - word2vec
========================================================

- 구글에서 발표한 워드임베딩 방법

워드임베딩 - GLoVE
========================================================

- GLoVe

워드임베딩 - fastText
========================================================

- 페이스북에서 만든 서브워드를 지원하는 임베딩 모델
- GPU가 없어도 매우 빠름
- 언어에 영향을 매우 적게 받음

워드임베딩 - BERT
========================================================

- 트랜스포머의 단순화 버전
- 현재까지 의미벡터를 만드는 방법 준에서 SOTA

Word2vec 구조
========================================================

그림 필요

워드벡터의 활용
========================================================

- 분류(Classification)
    - 신경망(Neural Network), SVM, Knn
- 군집화(Clutering)
    - K-means, DBSCAN

※ 기존에도 쓰던 것들이지만 좀더 그럴듯한 의미기반에 의한 결과가 나옴

워드벡터의 활용
========================================================

- 의미기반의 문서 검색
- 유사한 상품명 찾기, 의미 기반의 문서 분류
- 감성분류


워드벡터를 활용하기 위해 필요한 도구
========================================================

- 고속벡터검색엔진
    - Milvus, ElasticSearch, Vespa
    - Faiss

- [awesome vector search](https://github.com/currentslab/awesome-vector-search)

R패키지
=========================================================

TidyTexy

참고자료
=========================================================


- https://medium.com/broadhorizon-cmotions/nlp-with-r-part-2-training-word-embedding-models-and-visualize-results-ae444043e234
- https://rpubs.com/nabiilahardini/word2vec
- https://cran.r-project.org/web/packages/word2vec/readme/README.html
- https://cran.r-project.org/web/packages/text2vec/vignettes/glove.html
